### ISSUE TITLE
missing postinstall bower dependency

### ISSUE THREAD

**Issue by kolbma** [StErMi/openui5-qrcode#1]
If you do a postinstall with bower, you must not put bower in the devDependencies.

If the postinstall step is required put it in dependencies or if not in optional.

Isn't it possible that you don't need bower for installation of a npm package?

**Comment by kolbma** [comment]
What I can see is, you use bower to install openui5.  

Why you'd like to require the openui5 from bower?

1. It is outdated.
1. There are npm possibilities to depend on openui5.
1. You limit the developer on how he wants to provide openui5.

As a workaround you can `npm install --ignore-scripts openui5-qrcode`

**Comment by StErMi** [comment]
You are perfectly right. The idea was to update this build chain once the new ui5 build tool will be officially released with support to ui5 lib on npm ;)

**Comment by StErMi** [comment]
@kolbma I'm going to deprecate bower in all my libraries while I'm switching to ui5-tool ;)
